### ISSUE TITLE
[DOC] Clarification required for user manual

### ISSUE THREAD

**Issue by SEAJang** [LDAR-Sim/LDAR_Sim#104]
### Bug/Defect description

The upfront cost description in the user_manual can be confusing. 

### Steps to reproduce

N/A

### Evidence

Current User Manual:
<upfront>
Data type: Integer

Default input: 0

Description: The initial up-front cost of each crew. This cost is only charged once.

Notes on acquisition: Consult service provider.

Notes of caution: Does not account for maintenance activities or the cost of replacing devices at the end of their lifetime.

### Expected behavior

For methods set to stationary, the upfront cost is applied per site. 
However for mobile methods, the upfront cost is applied per crew. 

### Version Number

3.2

**Comment by ThomasGalesloot** [comment]
@SEAJang This can be closed as out of date right?

**Comment by SEAJang** [comment]
It was updated as of version 4.0
