### ISSUE TITLE
[BUG] menuinst v1.4.19 missing dependency for linux-64

### ISSUE THREAD

**Issue by ansxnlee** [LDAR-Sim/LDAR_Sim#111]
### Bug/Defect description

`./LDAR_Sim/install/requirements.txt` requires the menuinst v1.4.19 package but it only provides installers for win-32/win-64 based machines. This is the only package that doesn't include installers for linux.

Are there any alternatives aside from being forced to set up my local dev env with windows?

### Steps to reproduce

followed the provided installation instructions on an Ubuntu 20.04.5 LTS machine with python 3.8.10 and the latest version of miniconda.

### Evidence

heres a link to where the menuinst package is served: https://anaconda.org/conda-forge/menuinst

### Expected behavior

all packages should have been installed successfully.

### Version Number

v3.2.0

**Comment by lgolston** [comment]
I don't think the version of LDAR-Sim here on GitHub actually needs menuinst, or many of the other dependencies listed in requirements.txt.

**Comment by ThomasGalesloot** [comment]
Hi there, 

Sorry to hear that you ran into installation issues. Fortunately, menuinst just released version 2.0.0 which now has compatibility for linux and osx as well as windows. Our team will look into ensuring that installation from the requirements file will work for both windows and linux but in the meantime you could try changing the menuinst version number to install in the requirements.txt file from 1.4.19 to 2.0.0 or installing it to the conda environment separately.

Another potential installation issue to note is that you mentioned you are running python 3.8.10. The current requirements are for python 3.11. While you might be able to use 3.8.10 without issue, current requirements have not been tested for compatibility with that version of python.

If using the latest version of menuinst still results in installation issues, please follow-up and the LDAR-Sim team can help you troubleshoot your LDAR-Sim installation.

**Comment by ansxnlee** [comment]
i was able to run the main ldar_sim python script a couple weeks back after making the following changes:

- switched to python v3.11.3
- removed menuinst v1.4.19 entirely as a dependency as suggested by @lgolston  (though i suppose it should work with v2.0.0 now)
- downgraded pycosat v0.6.4 -> v0.6.3 (pip was complaining about the newer version missing)

**Comment by ThomasGalesloot** [comment]
@SEAJang has reviewed, updated and tested the requirements to ensure LDAR-Sim runs on Windows and Linux. Closing this issue as the update to the requirements has been merged into main (See commit f846df6b90f25c72cdcfafeaf0ccbde9170e7fb5) closing #129.
