### ISSUE TITLE
Add a regulatory calculated emissions

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [LDAR-Sim/LDAR_Sim#24]
Although LDAR-Sim knows when leaks begin we can calculate actual emissions, but in reality the start date is not known. Typically, emissions are calculated based on the survey time + 1/2 the time since last survey. This would be a helpful piece of equipment for comparing data to simulations, or planning carbon priced cost estimates.  Consider building in a user defined function (like module) for calculating this, to allow additional alternatives ie. survey time + 1/2 the time of last survey of a different method where the leak size was greater than the calculated methods MDL.

**Comment by SEAJang** [comment]
V4.0.0 has added in estimated emissions.
