### ISSUE TITLE
Subtype & facility File enhancement implementation

### ISSUE THREAD

**Issue by SEAJang** [LDAR-Sim/LDAR_Sim#25]
From subtype of facility file, users should be able to set the following parameters:

Program:
- LPR
- Leak Distribution
- NRD
- Repair Delay
- Vent Data *Will be tied to a different issue*
- Carbon Price *Will be tied to a different issue*
- Verification Cost/Repair cost

Method:
- RS
- Cost *Will be tied to a different issue*
- Coverage
- Deployment Months  (Scheduling) 
- Time_Btw_Sites 
- Time (on site time)

**Comment by KeeganShaw-GIS** [comment]
Should be a systematic way of implementation that allows new parameters.

**Comment by KeeganShaw-GIS** [comment]
Site level should always overwrite Subtype Level which should always overwrite method / Program Level

**Comment by SEAJang** [comment]
Semi-implemented. 
LPR, NRD, leak distribution can be set in a single subtype_file per subtype. 
Minor bug - the subtype_file cannot have a single entry, otherwise it will cause errors to occur, minimum 2 subtypes are needed for this file to work.

**Comment by ThomasGalesloot** [comment]
@SEAJang Can this issue be closed?

**Comment by SEAJang** [comment]
No longer relevant with v4 update.
