### ISSUE TITLE
Add ability for site-level measurement scale method to report fugitive emissions based on known venting

### ISSUE THREAD

**Issue by ThomasGalesloot** [LDAR-Sim/LDAR_Sim#58]
Add the ability to allow for site-level measurement scale method to report a site-level fugitive emissions measurement by subtracting expected venting rates from the measured site level emissions. This will reflect some real-world work practices, where screening methods are provided with planned/expected site venting rates before the screening so that they can account for venting when reporting/analyzing results.

**Comment by SEAJang** [comment]
No longer relevant with v4 update.
