### ISSUE TITLE
[BUG] Fix venting example unit test

### ISSUE THREAD

**Issue by SEAJang** [LDAR-Sim/LDAR_Sim#76]
### Bug/Defect description

Venting example unit tests are knowingly failing. 

### Steps to reproduce

Run unit tests.

### Evidence

![image](https://github.com/LDAR-Sim/LDAR_Sim/assets/43421303/536afacd-219a-4d0a-ad22-306f77c5904e)

### Expected behavior

All unit tests should pass. 

### Version Number

v2.14

**Comment by ThomasGalesloot** [comment]
Resolved - Issue was missed when closing issues related to the changes that resolved this issue
