### ISSUE TITLE
[FEAT] Add subtype survey times option to subtypes file

### ISSUE THREAD

**Issue by ThomasGalesloot** [LDAR-Sim/LDAR_Sim#84]
### Requested Feature/Enhancement

Add the functionality for users to provide method surveys types on a per subtype basis in the subtype file.

### Need for feature/Enhancement

Users can already provide subtype times on a per facility basis. This allows for user convenience when setting site behavior on a per subtype basis.

### Problem to solve

Allows for expanded subtype file functionality to make setting inputs more intuitive.

**Comment by SEAJang** [comment]
V4 addressed this enhancement.
