### ISSUE TITLE
[ENHANCEMENT] Remove E2E plots

### ISSUE THREAD

**Issue by ThomasGalesloot** [LDAR-Sim/LDAR_Sim#88]
### Requested Feature/Enhancement

Remove existing E2E plots and disable plots in E2E test case creator.

### Need for feature/Enhancement

Currently E2E tests track plots in their expected outputs. As all the values used to generate the plots are tracked in csv files and the plots are never used for verification of results, there is no need to track them for E2E tests.

### Problem to solve

Remove E2E plots and prevent new E2E tests from making plots.

### Implementation Ideas

N/A

### Additional context

N/A

**Comment by SEAJang** [comment]
No longer relevant with v4 update.
